### ISSUE TITLE
Fail to run inference on cpu

### ISSUE THREAD

**Issue by philippschw** [chandar-lab/AMPLIFY#10]
I would like to run inference on cpu in order to scale jobs cost effective unfortunately I fail to make it work.

I simply use : 
`predictor = amplify.inference.Predictor(model, tokenizer, device='cpu')
  sequence_embedding = predictor.embed(seqs)`

But get the following error: 
`NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(1, 50, 10, 64) (torch.float32)
     key         : shape=(1, 50, 10, 64) (torch.float32)
     value       : shape=(1, 50, 10, 64) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0
`decoderF` is not supported because:
    device=cpu (supported: {'cuda'})
    attn_bias type is <class 'NoneType'>
`flshattF@v2.3.6` is not supported because:
    device=cpu (supported: {'cuda'})
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
`tritonflashattF` is not supported because:
    device=cpu (supported: {'cuda'})
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
    operator wasn't built - see `python -m xformers.info` for more info
    triton is not available
`cutlassF` is not supported because:
    device=cpu (supported: {'cuda'})
`smallkF` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 32
    device=cpu (supported: {'cuda'})
    unsupported embed per head: 64`

I suspect it may be related to this message, which is appearing even on a CPU instance and whenever I import amplify: 
`[2024-10-31 10:49:28,626] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)`

I tried to set
`export DS_ACCELERATOR=cpu`
`accelerate launch --cpu run.py`

but without success.

**Comment by qfournier** [comment]
Hi, 

Thank you for your interest in AMPLIFY! 

Yes, this is a known limitation of the current codebase. The [`memory_efficient_attention`](https://facebookresearch.github.io/xformers/components/ops.html) from the `xformers` library only supports GPU, hence the error.

We are planning to add support for CPU inference by using [`torch.nn.functional.scaled_dot_product_attention`](https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html) in [`amplify.py`](https://github.com/chandar-lab/AMPLIFY/blob/c446678dfc8aa43d9e9fd39fa5d8b570012ff997/src/amplify/model/amplify.py#L153) when the tensors are on CPU instead of GPU. Note that I am a bit overloaded right now, so feel free to submit a PR if you have time!

**Comment by qfournier** [comment]
I've added CPU support to Hugging Face! The `xformers` implementation of the self-attention is used when the input is on GPU, while the default `torch` implementation is used on CPU.

You can compare the two implementations with the following code:
```python
import torch
from transformers import AutoModel
from transformers import AutoTokenizer
from datasets import load_dataset

# Load the UniProt validation set
dataset = load_dataset("chandar-lab/UR100P", data_dir="UniProt", split="test", streaming=True)

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained("chandar-lab/AMPLIFY_350M", trust_remote_code=True)

# CPU model
model_cpu = AutoModel.from_pretrained("chandar-lab/AMPLIFY_350M", trust_remote_code=True)

# GPU model
model_gpu = AutoModel.from_pretrained("chandar-lab/AMPLIFY_350M", trust_remote_code=True)
model_gpu = model_gpu.to("cuda")

for sample in dataset:
    input = tokenizer.encode(sample["sequence"], return_tensors="pt")
    output_cpu = torch.nn.functional.softmax(model_cpu(input)["logits"], dim=-1)
    output_gpu = torch.nn.functional.softmax(model_gpu(input.to("cuda"))["logits"].cpu(), dim=-1)
    print((output_cpu - output_gpu).pow(2).sum().sqrt())
```
