### ISSUE TITLE
Training scripts

### ISSUE THREAD

**Issue by damiano-sg** [chandar-lab/AMPLIFY#3]
Hi, great job!
As previously discussed, I was wondering whether you are planning to share some instructions on how you trained the different models for people who want to reproduce your results. That would be amazing :)
Thank you.

**Comment by qfournier** [comment]
Hi, 

I've just updated the `README.md` with instructions on how to pre-train AMPLIFY on a single machine as well as on a SLURM cluster. These are short instructions, so do not hesitate to let me know if some things are unclear.
